### ISSUE TITLE
Installation on Apple M1 not possible

### ISSUE THREAD

**Issue by dadebue** [pycompression/python-isal#107]
I'm trying to install isal with pip on my MacBook Pro 2021 (M1 Pro Chip on macOS Monterey 12.1)

The installation fails because of multiple errors. The first one being:
`In file included from erasure_code/aarch64/ec_aarch64_dispatcher.c:29:`
`/var/folders/yh/q11mmnrx4bj7m21b0l255mg40000gn/T/tmpmnogoka1/include/aarch64_multibinary.h:34:10: fatal error: asm/hwcap.h' file not found`
`#include <asm/hwcap.h>`
`           ^~~~~~~~~~~~~`
`  1 error generated.`

After that there are a bunch of other errors. I've added the full log as an attachment.

Is there anything I can do about that?

Cheers
Marco

[pip_install_isal_apple_m1.txt](https://github.com/pycompression/python-isal/files/7944121/pip_install_isal_apple_m1.txt)

**Comment by rhpvorderman** [comment]
Hi Marco,

That looks like a compile error for the included library ISA-L. That library does not yet support apple silicon mac, though a PR is in progress: https://github.com/intel/isa-l/pull/164 . I am affraid that is all that I can do for you at this moment. I do not own an M1 so I cannot help with adding support in the ISA-L library.

Best regards,
Ruben

**Comment by rhpvorderman** [comment]
Given that ISA-L was primarily designed for x86-64, it may take some time. May I suggest that you look at the Python bindings for libdeflate: https://github.com/dcwatson/deflate . It supports only gzip in memory compression and decompression, but it is quite fast. If that serves your use case you might not have to wait as long.

**Comment by rhpvorderman** [comment]
I see that has the isal_zlib import in a try except block.
He should make isal an optional dependency.
He can use the line from the xopen setup.cfg:
```
install_requires =
    isal>=0.9.0; platform_machine == "x86_64" or platform_machine == "AMD64"
```
Or for setup.py
```
    extras_require = {
        ':platform.machine == "x86_64" and '
        'python_implementation != "PyPy"': ['isal>=0.9.0'],
        ':platform.machine == "AMD64" and '
        'python_implementation != "PyPy"': ['isal>=0.9.0'],
    },
```
This way isal will install automatically, but not on unsupported machines.

**Comment by rhpvorderman** [comment]
I see this issue was solved in assammdf. Closing this now. 
Thanks for the bug report!
