### ISSUE TITLE
Release GIL inside library

### ISSUE THREAD

**Issue by asp437** [pycompression/python-isal#132]
The goal of the issue is to begin discussion about GIL manipulation in the library.

Currently, all the code inside the library is run in single thread since Python requires to acquire GIL to work with Python objects. As example this blocks using `isal` library in case of multiple concurrent threads each working with compressed file.

Have you consider releasing lock before executing I-SAL library functions that works with internal state (like `isal_deflate`)? I didn't fully checked all the details of I-SAL library and may miss some potential problems.

This is also one of the difference from built-in gzip implementation since it [releases lock before](https://github.com/python/cpython/blob/main/Modules/zlibmodule.c#L376) `deflate` call and `crc` calculation.

**Comment by rhpvorderman** [comment]
@asp437 doing so makes working in a single-thread slower, but I agree that it is worth the overhead. It will also make it more comparable to the CPython implementation. I will add this to the todo list.

> Have you consider releasing lock before executing I-SAL library functions that works with internal state (like isal_deflate)? I didn't fully checked all the details of I-SAL library and may miss some potential problems.

For compress and decompress it works fine. for the compressobj and decompressobj methods I believe the whole object is locked first in CPython to prevent the same state manipulated at the same time. So there shouldn't be any problems.

**Comment by asp437** [comment]
Sounds good.

I can try to prepare a PR if you want to. I don't have experience writing C extensions for Python yet. But I can try to prepare the PR since I have knowledge of both Python and C. Probably I'll need some help to polish it in later stages from your side.

**Comment by rhpvorderman** [comment]
No need. It is just a simple copy-paste operation from the zlibmodule.c in CPython. I prefer to do this work myself as I am quite picky about where exactly everything is copied. Trying to do this copy-paste through an external PR is not very efficient. 
I am very busy currently so I cannot do it right away. Also the following issue needs to be resolved #133 before I can make a release. If you know anybody who could help me with that it would be much appreciated. In that case I can also give a bit more priority to this.

**Comment by rhpvorderman** [comment]
@asp437 It has been done. You can install python-isal with `pip install git+https://github.com/pycompression/python-isal` . This will install the latest and greatest including GIL escaping. Make sure you have the requirements for the ISA-L build instructions installed: https://github.com/intel/isa-l#building-isa-l. Otherwise it won't compile.

**Comment by asp437** [comment]
Thank you, it was quite fast!

Will test it for my use cases in a few days.
