### ISSUE TITLE
igzip_threaded.open does not close opened file on error

### ISSUE THREAD

**Issue by marcelm** [pycompression/python-isal#172]
The `isal.igzip_threaded.open` function does not correctly close opened output files if an exception is raised due to an invalid compression level:
```bash
$ PYTHONDEVMODE=1 python3 -c 'from isal import igzip_threaded; igzip_threaded.open("out.gz", mode="wb", compresslevel=17).close()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../python3.10/site-packages/isal/igzip_threaded.py", line 71, in open
    _ThreadedGzipWriter(
  File ".../python3.10/site-packages/isal/igzip_threaded.py", line 211, in __init__
    self.compressors: List[isal_zlib._ParallelCompress] = [
  File ".../python3.10/site-packages/isal/igzip_threaded.py", line 212, in <listcomp>
    isal_zlib._ParallelCompress(buffersize=compress_buffer_size,
ValueError: Invalid compression level 17
sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name='out.gz'>
```
This is used in xopen:

https://github.com/pycompression/xopen/blob/0f1054014dcdc8e67004fac8a333d2295e84b08c/src/xopen/__init__.py#L1064-L1075

... and in turn makes some Cutadapt tests fail (because I have configured it so that unclosed files are an error).

The file is opened in line 61:
https://github.com/pycompression/python-isal/blob/5871c6f4a8906d1fbfcf56e4023ed6c3f80ff341/src/isal/igzip_threaded.py#L61

**Comment by rhpvorderman** [comment]
Thanks for reporting. I will try to fix it right away. (Might take until after the weekend to finish though).

**Comment by marcelm** [comment]
No worries, I can also pin to xopen 1.7 until this is fixed.

**Comment by rhpvorderman** [comment]
Done. Managed to reproduce the error and create a fix. Can you check if the "fixclosingbugs" branch I just pushed fixes your issues?

**Comment by marcelm** [comment]
Yes, thanks! see the PR

**Comment by rhpvorderman** [comment]
Currently releasing the wheels for 1.5.2
