### ISSUE TITLE
igzip_threaded cannot append

### ISSUE THREAD

**Issue by marcelm** [pycompression/python-isal#177]
An `xopen` test fails when isal 1.5.2 is installed. The problem can be reproduced thus:
```python
from isal.igzip_threaded import open as isal_open

with isal_open("out.gz", "wb") as f:
    f.write(b"AB")
with isal_open("out.gz", "ab") as f:
    f.write(b"CD")
with isal_open("out.gz", "rb") as f:
    contents = f.read()

assert contents == b"ABCD", contents
```
Fails with:
```
Traceback (most recent call last):
  File ".../test.py", line 10, in <module>
    assert contents == b"ABCD", contents
AssertionError: b'CD'
```
The assertion is not triggered with version 1.5.1.

**Comment by rhpvorderman** [comment]
Ah. That makes sense. 1.5.2 changed something in the opening code. I will fix that one right away.

**Comment by marcelm** [comment]
Thanks!

**Comment by rhpvorderman** [comment]
It has been released. Xopen tests should succeed again. Regression tests have been added.

**Comment by rhpvorderman** [comment]
Everything works again. Latest xopen commit functional: https://github.com/pycompression/xopen/actions/runs/6978308070/job/18992094506
