### ISSUE TITLE
need for submodules is not explained in README

### ISSUE THREAD

**Issue by gdt** [pycompression/python-isal#197]
I got hints from other PRs, but the need for submodules is not documented.  This is with today's git develop.

**Comment by rhpvorderman** [comment]
From the installation manual.

> The latest development version of python-isal can be installed with:

> `pip install git+https://github.com/rhpvorderman/python-isal.git`

This automatically installs the submodules. 

Can you specify what is lacking about not explicitly stating that there are submodules? It is not needed if the listed installation instructions are used.

**Comment by gdt** [comment]
I cloned the repo, because it was clear I was going to have to fix something, and ran setup.py.   I also, I think, tried to run pip passing the directory.   I definitely ended up with a "can't find Makefile.unx" error which was quite mysterious.

I don't understand your reluctance to just straightforwardly state the requirements.  Having that missing seems like an unnecessary barrier to use and contributions.

I look at a readme to be for people using the source.  It seems entirely fine to put installation instructions in INSTALL.md and have only a line or two in readme to say "see INSTALL.md for installation".

**Comment by rhpvorderman** [comment]
> I think instructions should help people building modified versions from local repos, not just building from unmodified github.

Clear, I could add a small development chapter in the documentation which would state to use "git clone --recursive" etc and also provide a link to the ISA-L list of build requirements. I could link that from the README. 

> I don't understand your reluctance to just straightforwardly state the requirements.

That's not an entirely accurate rendition of my position. I do not want to clutter the landing page with very detailed information that is irrelevant to most users. Having said that, your suggestion to provide detailed instructions linked from the README also works for me. I will put this on the to-do list.

**Comment by gdt** [comment]
Great, thanks.  I do understand the githubby landing page notion, even though I come from an earlier time :-)

**Comment by rhpvorderman** [comment]
A recursive clone is now recommended on the README.
